version: '3.4'

services:
  costprice:
    image: auth-peer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - redis
      - elasticsearch 
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies            
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
  redis:
    image: redis:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data    
volumes:
  esdata:    
