version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
      - elasticsearch 
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules  # Include this line to mount the node_modules directory
    environment:
      - NODE_ENV=development          
  redis:
    image: redis:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data    
volumes:
  esdata: